// aiMock.js
// This simulates an on-device Vision-Language Model (VLM) running on the Snapdragon NPU.

/**
 * Simulates analyzing an image to detect UI wireframe elements.
 * @param {string} imageSrc - Base64 or Blob URL of the captured image
 * @returns {Promise<string>} - The generated React code string
 */
export const analyzeWireframe = async (imageSrc) => {
  // Simulate NPU inference delay (e.g., 2.5 seconds for a quantized edge model)
  return new Promise((resolve) => {
    setTimeout(() => {
      const generatedCode = `
import React, { useState } from 'react';
import './WireframeStyles.css';

// 🤖 Generated by WireSnap NPU
export default function GeneratedLoginScreen() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = (e) => {
    e.preventDefault();
    console.log("Logging in...", { email, password });
  };

  return (
    <div className="login-container">
      <div className="login-card glass-panel">
        <h2 className="login-title">Welcome Back</h2>
        <p className="login-subtitle">Sign in to continue</p>
        
        <form onSubmit={handleLogin} className="login-form">
          <div className="input-group">
            <label>Email Address</label>
            <input 
              type="email" 
              placeholder="name@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>
          
          <div className="input-group">
            <label>Password</label>
            <input 
              type="password" 
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>
          
          <button type="submit" className="login-button pulse-button">
            Sign In
          </button>
        </form>
      </div>
    </div>
  );
}
`;
      resolve(generatedCode.trim());
    }, 2500); // 2.5s delay to make the demo feel realistic
  });
};
