package com.iqoo.insideme.domain

enum class FindingCategory {
    INFORMATIONAL,
    ATTENTION,
    FOLLOW_UP,
    UNKNOWN
}

enum class FindingStatus {
    NEW,
    REVIEWED,
    ACTIONED,
    DISMISSED
}

enum class TaskStatus {
    OPEN,
    COMPLETED,
    DISMISSED
}

data class Finding(
    val id: String,
    val title: String,
    val description: String,
    val category: FindingCategory,
    val confidence: Float,
    val evidenceIds: List<String>,
    val detectedChangeIds: List<String>,
    val suggestedActions: List<String>,
    val status: FindingStatus
)

class RuleEngine {
    fun evaluateChanges(changes: List<DetectedChange>): FindingCategory {
        // Deterministic safety check
        val hasHighSeverity = changes.any { it.severity == ChangeSeverity.HIGH }
        val hasMediumSeverity = changes.any { it.severity == ChangeSeverity.MEDIUM }
        
        return when {
            hasHighSeverity -> FindingCategory.FOLLOW_UP
            hasMediumSeverity -> FindingCategory.ATTENTION
            else -> FindingCategory.INFORMATIONAL
        }
    }
}

class RecommendationEngine {
    fun generateRecommendation(
        findingCategory: FindingCategory,
        changes: List<DetectedChange>,
        llmExplanation: String
    ): Finding {
        val evidenceIds = changes.flatMap { listOf(it.previousEvidenceId, it.currentEvidenceId) }.distinct()
        val changeIds = changes.map { it.id }
        
        val suggestedActions = mutableListOf<String>()
        if (findingCategory == FindingCategory.FOLLOW_UP) {
            suggestedActions.add("Schedule a physical inspection of the affected component.")
        }
        suggestedActions.add("Add note to memory log.")
        
        // Ensure no fake precision/percentages
        val confidenceRating = if (changes.isNotEmpty() && evidenceIds.size >= 2) 0.95f else 0.50f
        
        return Finding(
            id = "finding_${System.currentTimeMillis()}",
            title = if (findingCategory == FindingCategory.FOLLOW_UP) "Action Required" else "Observation Detected",
            description = llmExplanation,
            category = findingCategory,
            confidence = confidenceRating,
            evidenceIds = evidenceIds,
            detectedChangeIds = changeIds,
            suggestedActions = suggestedActions,
            status = FindingStatus.NEW
        )
    }
}

class LocalReportGenerator {
    fun generateReport(
        subjectName: String,
        dateRange: String,
        changes: List<DetectedChange>,
        finding: Finding
    ): String {
        val sb = StringBuilder()
        sb.append("# INSIDEME AI Inspection Report\n\n")
        sb.append("**Subject**: $subjectName\n")
        sb.append("**Observation Period**: $dateRange\n\n")
        
        sb.append("## Detected Changes\n")
        changes.forEachIndexed { index, change ->
            sb.append("${index + 1}. ${change.description}\n")
        }
        sb.append("\n")
        
        sb.append("## Findings & Analysis\n")
        sb.append("Category: ${finding.category}\n")
        sb.append("Evidence Strength: ${if (finding.confidence > 0.8f) "Strong" else "Moderate"}\n\n")
        sb.append("${finding.description}\n\n")
        
        sb.append("## Suggested Follow-up\n")
        finding.suggestedActions.forEach { action ->
            sb.append("- $action\n")
        }
        
        sb.append("\n---\n*Generated by InsideMe AI locally. Human review required.*\n")
        return sb.toString()
    }
}
